services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33061:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: wp
    depends_on:
      - db
    #image: versionpress/wordpress:php7.2-apache@sha256:64b3c10adfef9ae65a140d5547d670d996c5c852b9a840c71a86a5be4f777fdc
    image: ggiorgino/wordpress
    ports:
      - 80:80
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      APACHE_DOCUMENT_ROOT: "/var/www/html"
    volumes:
      - ./versionpress/plugins/versionpress:/var/www/html/wp-content/plugins/versionpress:z
      - ./versionpress/plugins/versionpress:/var/www/staging/wp-content/plugins/versionpress:z
      - ./wp1/html:/var/www/html
      - ./wp2/staging:/var/www/staging
      - ./wp2.conf:/etc/apache2/sites-available/wp2.conf
    user: "33"
    #command: 
    # docker compose exec -it -u root wordpress bash -c "a2ensite wp2 && service apache2 reload"
    # docker compose exec -it wordpress wp core install --path="/var/www/html" --url="http://wp1" --title=My_wp --admin_user=greg --admin_password=greg --admin_email=giorgino.greg@gmail.com --skip-email;  
    # docker compose exec -it wordpress wp plugin activate versionpress 
    # docker compose exec -it wordpress wp vp activate --yes 
    # docker compose exec -it wordpress wp vp clone --name=staging --siteurl="http://wp2" 
    #wordpress_2:
    #  container_name: wp-2
    #  depends_on:
    #    - db
    #  #image: versionpress/wordpress:php7.2-apache@sha256:64b3c10adfef9ae65a140d5547d670d996c5c852b9a840c71a86a5be4f777fdc
    #  image: ggiorgino/wordpress
    #  ports:
    #    - 8002:80
    #  restart: always
    #  extra_hosts:
    #    - "host.docker.internal:host-gateway"
    #  environment:
    #    WORDPRESS_DB_HOST: db:3306
    #    WORDPRESS_DB_NAME: wordpress
    #    WORDPRESS_DB_USER: wordpress
    #    WORDPRESS_DB_PASSWORD: wordpress
    #    WORDPRESS_TABLE_PREFIX: "wp_staging_"
    #    APACHE_DOCUMENT_ROOT: "/var/www/staging"
    #    WORDPRESS_DEBUG: 1
    #  volumes:
    #    - 769ed7253e6675a84425cec74cec5ab1c52edc36865a35378eefaea7993592a8:/var/www/html
    #    - 437e35614b84e4b3b6355c96f5cb0adf9a44f32543715379d09ebc782ac9983c:/var/www/staging
    #    - ./versionpress/plugins/versionpress:/var/www/staging/wp-content/plugins/versionpress:z

volumes:
  db_data:
